### numpy array

In [1]:
import numpy as np

In [10]:
a = np.array([[1,2,3],[1,5,9],[3,5,7]])

# number of array dimension
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)

[[1 2 3]
 [1 5 9]
 [3 5 7]]
2
(3, 3)
9
int64


In [19]:
# create array with elements in 0
a = np.zeros((2,3))
print(a)

# create array with elements in 1
b = np.ones((2,3))
print(b)

# create array with elements in unspecified value
c = np.empty((2,2))
print(c)

# create array with values in multiple of 5 from 10 to 30
d = np.arange(10,30,5)
print(d)

# create array with elements in 4
e = np.full((2,2),4)
print(e)

# 3x3 matrix 
f = np.eye(3)
print(f)

# create array with random values
g = np.random.random((2,2))
print(g)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[2.27610064e-314 2.20180060e-314]
 [2.20183288e-314 2.20116257e-314]]
[10 15 20 25]
[[4 4]
 [4 4]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0.52482156 0.81331972]
 [0.2543198  0.98470216]]


### numpy indexing/slicing

In [21]:
a = np.array([1,2,3,4,5,6,7])

# index3
print(a[3])
# value in last index
print(a[-1])
# index2 to 4
print(a[2:5])
# index 2 to the end
print(a[2: ])
# index0 to 3
print(a[ :4])

4
7
[3 4 5]
[3 4 5 6 7]
[1 2 3 4]


In [23]:
a = np.array([[ 1, 2, 3],
              [ 4, 5, 6],
              [ 7, 8, 9]])

print(a[1,2])
# column 1
print(a[ : ,1])
# row 1
print(a[1, :])
# last row
print(a[-1])

6
[2 5 8]
[4 5 6]
[7 8 9]


### numpy reshaping

In [25]:
a = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]])

# create 1d array
print(a.ravel())
# reshape into [2][6]array
print(a.reshape(2,6))
# transpose array
print(a.T)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [28]:
b = np.array([[1,2,3],
                    [5,6,7],
                    [9,10,11],
                    [12,13,14]])

# reshape array with 3 row
# 3행만 지정해주고 열에 -1을 넣으면 자동으로 배열을 reshape한다.
print(b.reshape(3,-1))

[[ 1  2  3  5]
 [ 6  7  9 10]
 [11 12 13 14]]
